// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// ObjectStoreMock is a mock implementation of api.ObjectStore.
//
//	func TestSomethingThatUsesObjectStore(t *testing.T) {
//
//		// make and configure a mocked api.ObjectStore
//		mockedObjectStore := &ObjectStoreMock{
//			ExistsFunc: func(ctx context.Context, key string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			PresignGetFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the PresignGet method")
//			},
//			PresignPutFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the PresignPut method")
//			},
//		}
//
//		// use mockedObjectStore in code that requires api.ObjectStore
//		// and then make assertions.
//
//	}
type ObjectStoreMock struct {
	// ExistsFunc mocks the Exists method.
	ExistsFunc func(ctx context.Context, key string) (bool, error)

	// PresignGetFunc mocks the PresignGet method.
	PresignGetFunc func(ctx context.Context, key string) (string, error)

	// PresignPutFunc mocks the PresignPut method.
	PresignPutFunc func(ctx context.Context, key string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// PresignGet holds details about calls to the PresignGet method.
		PresignGet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// PresignPut holds details about calls to the PresignPut method.
		PresignPut []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
	}
	lockExists     sync.RWMutex
	lockPresignGet sync.RWMutex
	lockPresignPut sync.RWMutex
}

// Exists calls ExistsFunc.
func (mock *ObjectStoreMock) Exists(ctx context.Context, key string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("ObjectStoreMock.ExistsFunc: method is nil but ObjectStore.Exists was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(ctx, key)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedObjectStore.ExistsCalls())
func (mock *ObjectStoreMock) ExistsCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// PresignGet calls PresignGetFunc.
func (mock *ObjectStoreMock) PresignGet(ctx context.Context, key string) (string, error) {
	if mock.PresignGetFunc == nil {
		panic("ObjectStoreMock.PresignGetFunc: method is nil but ObjectStore.PresignGet was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockPresignGet.Lock()
	mock.calls.PresignGet = append(mock.calls.PresignGet, callInfo)
	mock.lockPresignGet.Unlock()
	return mock.PresignGetFunc(ctx, key)
}

// PresignGetCalls gets all the calls that were made to PresignGet.
// Check the length with:
//
//	len(mockedObjectStore.PresignGetCalls())
func (mock *ObjectStoreMock) PresignGetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockPresignGet.RLock()
	calls = mock.calls.PresignGet
	mock.lockPresignGet.RUnlock()
	return calls
}

// PresignPut calls PresignPutFunc.
func (mock *ObjectStoreMock) PresignPut(ctx context.Context, key string) (string, error) {
	if mock.PresignPutFunc == nil {
		panic("ObjectStoreMock.PresignPutFunc: method is nil but ObjectStore.PresignPut was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockPresignPut.Lock()
	mock.calls.PresignPut = append(mock.calls.PresignPut, callInfo)
	mock.lockPresignPut.Unlock()
	return mock.PresignPutFunc(ctx, key)
}

// PresignPutCalls gets all the calls that were made to PresignPut.
// Check the length with:
//
//	len(mockedObjectStore.PresignPutCalls())
func (mock *ObjectStoreMock) PresignPutCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockPresignPut.RLock()
	calls = mock.calls.PresignPut
	mock.lockPresignPut.RUnlock()
	return calls
}
