// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/pkarpovich/allspeak-catalog/internal/store"
	"sync"
)

// SessionStoreMock is a mock implementation of api.SessionStore.
//
//	func TestSomethingThatUsesSessionStore(t *testing.T) {
//
//		// make and configure a mocked api.SessionStore
//		mockedSessionStore := &SessionStoreMock{
//			CreateFunc: func(ctx context.Context, session store.Session) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (store.Session, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]store.Session, error) {
//				panic("mock out the List method")
//			},
//			UpdateManifestFunc: func(ctx context.Context, session store.Session) (int, error) {
//				panic("mock out the UpdateManifest method")
//			},
//		}
//
//		// use mockedSessionStore in code that requires api.SessionStore
//		// and then make assertions.
//
//	}
type SessionStoreMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, session store.Session) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (store.Session, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]store.Session, error)

	// UpdateManifestFunc mocks the UpdateManifest method.
	UpdateManifestFunc func(ctx context.Context, session store.Session) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Session is the session argument value.
			Session store.Session
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateManifest holds details about calls to the UpdateManifest method.
		UpdateManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Session is the session argument value.
			Session store.Session
		}
	}
	lockCreate         sync.RWMutex
	lockDelete         sync.RWMutex
	lockGet            sync.RWMutex
	lockList           sync.RWMutex
	lockUpdateManifest sync.RWMutex
}

// Create calls CreateFunc.
func (mock *SessionStoreMock) Create(ctx context.Context, session store.Session) error {
	if mock.CreateFunc == nil {
		panic("SessionStoreMock.CreateFunc: method is nil but SessionStore.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Session store.Session
	}{
		Ctx:     ctx,
		Session: session,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, session)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedSessionStore.CreateCalls())
func (mock *SessionStoreMock) CreateCalls() []struct {
	Ctx     context.Context
	Session store.Session
} {
	var calls []struct {
		Ctx     context.Context
		Session store.Session
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *SessionStoreMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("SessionStoreMock.DeleteFunc: method is nil but SessionStore.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedSessionStore.DeleteCalls())
func (mock *SessionStoreMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *SessionStoreMock) Get(ctx context.Context, id string) (store.Session, error) {
	if mock.GetFunc == nil {
		panic("SessionStoreMock.GetFunc: method is nil but SessionStore.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSessionStore.GetCalls())
func (mock *SessionStoreMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *SessionStoreMock) List(ctx context.Context) ([]store.Session, error) {
	if mock.ListFunc == nil {
		panic("SessionStoreMock.ListFunc: method is nil but SessionStore.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedSessionStore.ListCalls())
func (mock *SessionStoreMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// UpdateManifest calls UpdateManifestFunc.
func (mock *SessionStoreMock) UpdateManifest(ctx context.Context, session store.Session) (int, error) {
	if mock.UpdateManifestFunc == nil {
		panic("SessionStoreMock.UpdateManifestFunc: method is nil but SessionStore.UpdateManifest was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Session store.Session
	}{
		Ctx:     ctx,
		Session: session,
	}
	mock.lockUpdateManifest.Lock()
	mock.calls.UpdateManifest = append(mock.calls.UpdateManifest, callInfo)
	mock.lockUpdateManifest.Unlock()
	return mock.UpdateManifestFunc(ctx, session)
}

// UpdateManifestCalls gets all the calls that were made to UpdateManifest.
// Check the length with:
//
//	len(mockedSessionStore.UpdateManifestCalls())
func (mock *SessionStoreMock) UpdateManifestCalls() []struct {
	Ctx     context.Context
	Session store.Session
} {
	var calls []struct {
		Ctx     context.Context
		Session store.Session
	}
	mock.lockUpdateManifest.RLock()
	calls = mock.calls.UpdateManifest
	mock.lockUpdateManifest.RUnlock()
	return calls
}
